**Install Libraries**

In [ ]:
pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.5.20)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

**Import Libraries**

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

**Send Request & Parse HTML**

In [ ]:
url = "https://books.toscrape.com"
response = requests.get(url)

soup = BeautifulSoup(response.content, "html.parser")
print("Status Code:", response.status_code)
print("Page Title:", soup.title.text)

Status Code: 200
Page Title:
    All products | Books to Scrape - Sandbox

**Scrape All Pages**

In [ ]:
books = []
page = 1

while True:
    url = f"https://books.toscrape.com/catalogue/page-{page}.html"
    response = requests.get(url)

    if response.status_code != 200:
        break  # Stop when no more pages

    soup = BeautifulSoup(response.content, "html.parser")
    articles = soup.find_all("article", class_="product_pod")

    for book in articles:
        title = book.h3.a["title"]
        price = book.find("p", class_="price_color").text.strip()
        rating = book.p["class"][1]  # One, Two, Three, Four, Five
        availability = book.find("p", class_="instock availability").text.strip()

        books.append({
            "Title": title,
            "Price": price,
            "Rating": rating,
            "Availability": availability
        })

    print(f"Scraped page {page}")
    page += 1

print(f"\nTotal books scraped: {len(books)}")

Scraped page 1
Scraped page 2
Scraped page 3
Scraped page 4
Scraped page 5
Scraped page 6
Scraped page 7
Scraped page 8
Scraped page 9
Scraped page 10
Scraped page 11
Scraped page 12
Scraped page 13
Scraped page 14
Scraped page 15
Scraped page 16
Scraped page 17
Scraped page 18
Scraped page 19
Scraped page 20
Scraped page 21
Scraped page 22
Scraped page 23
Scraped page 24
Scraped page 25
Scraped page 26
Scraped page 27
Scraped page 28
Scraped page 29
Scraped page 30
Scraped page 31
Scraped page 32
Scraped page 33
Scraped page 34
Scraped page 35
Scraped page 36
Scraped page 37
Scraped page 38
Scraped page 39
Scraped page 40
Scraped page 41
Scraped page 42
Scraped page 43
Scraped page 44
Scraped page 45
Scraped page 46
Scraped page 47
Scraped page 48
Scraped page 49
Scraped page 50

Total books scraped: 1000

**Convert to DataFrame**

In [ ]:
df = pd.DataFrame(books)
print(df.shape)
df.head(10)

(1000, 4)

,Title,Price,Rating,Availability
0,A Light in the Attic,£51.77,Three,In stock
1,Tipping the Velvet,£53.74,One,In stock
2,Soumission,£50.10,One,In stock
3,Sharp Objects,£47.82,Four,In stock
4,Sapiens: A Brief History of Humankind,£54.23,Five,In stock
5,The Requiem Red,£22.65,One,In stock
6,The Dirty Little Secrets of Getting Your Dream...,£33.34,Four,In stock
7,The Coming Woman: A Novel Based on the Life of...,£17.93,Three,In stock
8,The Boys in the Boat: Nine Americans and Their...,£22.60,Four,In stock
9,The Black Maria,£52.15,One,In stock

**Basic Analysis**

In [ ]:
# Convert price to float
df["Price"] = df["Price"].str.replace("Â£", "").str.replace("£", "").astype(float)

print("Average Price: £", round(df["Price"].mean(), 2))
print("\nRating Distribution:")
print(df["Rating"].value_counts())
print("\nAvailability Count:")
print(df["Availability"].value_counts())

Average Price: £ 35.07

Rating Distribution:
Rating
One      226
Three    203
Five     196
Two      196
Four     179
Name: count, dtype: int64

Availability Count:
Availability
In stock    1000
Name: count, dtype: int64

**Save to CSV**

In [ ]:
 df.to_csv("books_data.csv", index=False)
print("Data saved to books_data.csv")
df.head()

Data saved to books_data.csv

                                   Title  Price Rating Availability
0                   A Light in the Attic  51.77  Three     In stock
1                     Tipping the Velvet  53.74    One     In stock
2                             Soumission  50.10    One     In stock
3                          Sharp Objects  47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  54.23   Five     In stock

 **Download CSV**

In [ ]:
from google.colab import files
files.download("books_data.csv")

In [ ]:
!git config --global user.email "pcmohith@gmail.com"
!git config --global user.name "Mohith-PC"

!git remote remove origin
!git remote add origin https://Mohith-PC:YOUR_TOKEN_HERE@github.com/Mohith-PC/CodeAlpha_WebScraping.git
!git branch -M main
!git push -u origin main

remote: Invalid username or token. Password authentication is not supported for Git operations.
fatal: Authentication failed for 'https://github.com/Mohith-PC/CodeAlpha_WebScraping.git/'